name: build
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v2
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'microsoft'
      - run: chmod +x ./gradlew
      - run: ./gradlew build --warning-mode fail --stacktrace